config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  scope module: :public do
   root to: 'homes#top'
   get 'about' => 'homes#about'

   resources :items, only: [:index, :show]
   post 'orders/confirm(/:id)', to: 'orders#confirm', as: 'confirm_order'
   get 'orders/complete', to: 'orders#complete', as: 'complete_order'
   resources :orders, only: [:new, :create, :index, :show]
   resources :addresses, only: [:index, :edit, :create, :update, :destroy]
   patch 'customers/withdraw', to: 'customers#withdraw', as: 'withdraw_customer'
   get 'customers/unsubscribe', to: 'customers#unsubscribe', as: 'unsubscribe_customer'
   resources :customers, only: [:show, :edit, :update]
   resources :cart_items, only: [:index, :update, :create, :destroy] do
     collection do
     delete 'destroy_all'
    end
   end
  end

  namespace :admin do
   get 'top' => 'homes#top'
   patch 'order_details/update/:id', to: 'order_details#update', as: 'update_order_details'
   resources :items, only: [:index, :new, :create, :show, :edit, :update]
   resources :genres, only: [:index, :create, :edit, :update]
   resources :customers, only: [:index, :show, :edit, :update]
   resources :orders, only: [:show, :update]
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  def address_display
    "〒" + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  def subtotal
    item.with_tax_price * amount
  end
  validates :amount, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :addresses, dependent: :destroy
         has_many :cart_items, dependent: :destroy
         has_many :orders, dependent: :destroy

  def fullname
    first_name + last_name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre
  attachment :image
  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { wait: 0, confirmation: 1, production: 2, preparing_to_ship: 3, done: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order
  enum making_status: { impossible: 0, wait: 1, production: 2, completion: 3 }
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    customer = Customer.find(params[:id])
    customer.update(customer_params)
    redirect_to admin_customer_path(customer.id)
  end

  private
  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def create
    @genre =Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def update
    genre_edit = Genre.find(params[:id])
    genre_edit.update(genre_params)
    redirect_to admin_genres_path(genre_edit.id)
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all.page(params[:page]).per(8)
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    item = Item.new(item_params)
    item.save
    redirect_to admin_items_path
  end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
    @genre = @item.genre
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_items_path(item.id)
  end

  private
  def item_params
    params.require(:item).permit(:name, :image, :introduction, :genre_id, :price, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def update
    order = Order.find(params[:id])
    order.update(order_params)
    redirect_to admin_top_path
  end

  private
  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="offset-md-2 col-md-8 offset-md-2">
      <h2><%= @customer.fullname %>さんの会員詳細</h2>
      <%= form_with model:@customer, url:admin_customer_path, methot: :patch, local: true do |f| %>
        <table>
          <tr>
            <th>会員ID</th>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <th>氏名</th>
            <td><%= f.text_field :first_name %>　<%= f.text_field :last_name %></td>
          </tr>
          <tr>
            <th>フリガナ</th>
            <td><%= f.text_field :first_name_kana %>　<%= f.text_field :last_name_kana %></td>
          </tr>
          <tr>
            <th>郵便番号</th>
            <td><%= f.text_field :postal_code, autofocus:true %></td>
          </tr>
          <tr>
            <th>住所</th>
            <td><%= f.text_field :address, autofocus:true %></td>
          </tr>
          <tr>
            <th>電話番号</th>
            <td><%= f.telephone_field :telephone_number, autofocus:true %></td>
          </tr>
          <tr>
            <th>メールアドレス</th>
            <td><%= f.email_field :email, autofocus: true, autocomplete: "email" %></td>
          </tr>
          <tr>
            <th>会員ステータス</th>
            <td>
              <%= f.radio_button :is_deleted, false %>有効
              <%= f.radio_button :is_deleted, true %>退会
            </td>
          </tr>
          <tr>
            <th></th>
            <td><%= f.submit '変更を保存', class: "btn btn-success" %></td>
          </tr>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="offset-md-2 col-md-8 offset-md-2">
      <h1>会員一覧</h1>
      <table class="table">
        <thead>
            <tr>
              <th>会員ID</th>
              <th>氏名</th>
              <th>メールアドレス</th>
              <th>ステータス</th>
            </tr>
        </thead>
        <% @customers.each do |f| %>
          <tbody>
            <tr>
              <td><%= f.id %></td>
              <td>
                <%= link_to f.fullname, admin_customer_path(f.id) %>
              </td>
              <td><%= f.email %></td>
              <td>
                <% if f.is_deleted == false %>
                  有効
                <% else %>
                  退会
                <% end %>
              </td>
            </tr>
          </tbody>
        <% end %>
      </table>
      <%= paginate @customers %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="offset-md-2 col-md-8 offset-md-2">
      <h2><%= @customer.fullname %>さんの会員詳細</h2>
      <table>
        <tr>
          <th>会員ID</th>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <th>氏名</th>
          <td><%= @customer.first_name %>　<%= @customer.last_name %></td>
        </tr>
        <tr>
          <th>フリガナ</th>
          <td><%= @customer.first_name_kana %>　<%= @customer.last_name_kana %></td>
        </tr>
        <tr>
          <th>郵便番号</th>
          <td><%= @customer.postal_code %></td>
        </tr>
        <tr>
          <th>住所</th>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <th>電話番号</th>
          <td><%= @customer.telephone_number %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <th>会員ステータス</th>
          <td>
            <% if @customer.is_deleted == false %>
              有効
            <% else %>
              退会
            <% end %>
          </td>
        </tr>
      </table>
    </div>
    <div class="offset-md-2 col-md-2">
      <%= link_to "編集する", edit_admin_customer_path(@customer.id), class: "btn btn-success" %>
    </div>
    <div class="col-md-4">
      <%= link_to "注文履歴一覧を見る", admin_top_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>