config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  scope module: :public do
   root to: 'homes#top'
   get 'about' => 'homes#about'

   resources :items, only: [:index, :show]
   post 'orders/confirm(/:id)', to: 'orders#confirm', as: 'confirm_order'
   get 'orders/complete', to: 'orders#complete', as: 'complete_order'
   resources :orders, only: [:new, :create, :index, :show]
   resources :addresses, only: [:index, :edit, :create, :update, :destroy]
   patch 'customers/withdraw', to: 'customers#withdraw', as: 'withdraw_customer'
   get 'customers/unsubscribe', to: 'customers#unsubscribe', as: 'unsubscribe_customer'
   resources :customers, only: [:show, :edit, :update]
   resources :cart_items, only: [:index, :update, :create, :destroy] do
     collection do
     delete 'destroy_all'
    end
   end
  end

  namespace :admin do
   get 'top' => 'homes#top'
   patch 'order_details/update/:id', to: 'order_details#update', as: 'update_order_details'
   resources :items, only: [:index, :new, :create, :show, :edit, :update]
   resources :genres, only: [:index, :create, :edit, :update]
   resources :customers, only: [:index, :show, :edit, :update]
   resources :orders, only: [:show, :update]
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  def address_display
    "〒" + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  def subtotal
    item.with_tax_price * amount
  end
  validates :amount, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :addresses, dependent: :destroy
         has_many :cart_items, dependent: :destroy
         has_many :orders, dependent: :destroy

  def fullname
    first_name + last_name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre
  attachment :image
  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { wait: 0, confirmation: 1, production: 2, preparing_to_ship: 3, done: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order
  enum making_status: { impossible: 0, wait: 1, production: 2, completion: 3 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def create
    @genre =Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def update
    genre_edit = Genre.find(params[:id])
    genre_edit.update(genre_params)
    redirect_to admin_genres_path(genre_edit.id)
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all.page(params[:page]).per(8)
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    item = Item.new(item_params)
    item.save
    redirect_to admin_items_path
  end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
    @genre = @item.genre
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_items_path(item.id)
  end

  private
  def item_params
    params.require(:item).permit(:name, :image, :introduction, :genre_id, :price, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def update
    order = Order.find(params[:id])
    order.update(order_params)
    redirect_to admin_top_path
  end

  private
  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h4>ジャンル編集</h4>
      <%= form_with model:@genre, url:admin_genre_path, method: :patch, local: true do |f| %>
        <p>ジャンル名</p>
        <%= f.text_field :name %>
        <%= f.submit '変更を保存' %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h4>ジャンル一覧・追加</h4>
      <%= form_with model: @genre, url: admin_genres_path, method: :post, local:true do |f| %>
        <%= f.label :ジャンル名 %>
        <%= f.text_field :name %>
        <%= f.submit '新規投稿', class: "btn btn-success" %>
        <table class="table">
          <thead>
            <tr>
              <th>ジャンル</th>
            </tr>
              <% @genres.each do |genre| %>
            <tr>
                <td><%= genre.name %></td>
                <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-success" %></td>
            </tr>
              <% end %>
          </thead>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="offset-md-2 col-md-8 offset-md-2">
      <h4>商品編集</h4>
      <%= form_with model:@item, url:admin_item_path, methot: :patch, local: true do |f| %>
        <p>商品画像</p>
          <%= f.attachment_field :image %>
        <p>商品名</p>
          <%= f.text_field :name %>
        <p>商品説明</p>
          <%= f.text_area :introduction %>
        <p>ジャンル</p>
          <%= f.collection_select(:genre_id, @genres, :id, :name) %>
        <p>税抜価格</p>
          <%= f.number_field :price %>円
        <p>販売ステータス</p>
          <%= f.radio_button :is_active, true %>販売中
          <%= f.radio_button :is_active, false %>販売停止中
        <p><%= f.submit '変更を保存', class: "btn btn-success" %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="offset-md-2 col-md-4">
    <h4>商品一覧</h4>
    </div>
    <div class="¥col-md-4 offset-md-2">
      <%= link_to "+", new_admin_item_path, class: "btn btn-light rounded-circle p-0", style: "width:2rem;height:2rem;" %>
    </div>
    <div class="offset-md-2 col-md-8 offset-md-2">
      <table class="table">
        <thead>
          <tr>
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
          </tr>
          <% @items.each do |item| %>
            <tr>
              <td><%= item.id %></td>
              <td><%= link_to item.name, admin_item_path(item.id) %></td>
              <td><%= item.price %></td>
              <td><%= item.genre.name %></td>
              <% if item.is_active == true %>
                <td>販売中</td>
              <% else %>
                <td>販売停止中</td>
              <% end %>
            </tr>
          <% end %>
        </thead>
      </table>
      <%= paginate @items %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="offset-md-2 col-md-8 offset-md-2">
      <h4>商品新規登録</h4>
      <%= form_with model: @item, url:admin_items_path, local:true do |f| %>
        <p>商品画像</p>
          <%= f.attachment_field :image %>
        <p>商品名</p>
          <%= f.text_field :name %>
        <p>商品説明</p>
          <%= f.text_area :introduction %>
        <p>ジャンル</p>
          <%= f.collection_select(:genre_id, @genres, :id, :name) %>
        <p>税抜価格</p>
          <%= f.number_field :price %>円
        <p>販売ステータス</p>
          <%= f.radio_button :is_active, true %>販売中
          <%= f.radio_button :is_active, false %>販売停止中
        <p><%= f.submit '新規投稿', class: "btn btn-success" %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row">
    <div class="offset-md-2 col-md-2">
      <h4>商品詳細</h4>
      <%= attachment_image_tag @item, :image, size:"200x200", fallback: "no_image.jpg" %>
    </div>
    <div class="col-md-4 offset-md-2">
      <P><%= @item.name %></P>
      <p><%= @item.introduction %></p>
      <p><%= @genre.name %></p>
      <p><%= @item.price %></p>
      <p>
        <% if @item.is_active == true %>
          <td>販売中</td>
        <% else %>
          <td>販売停止中</td>
        <% end %>
      </p>
      <%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-success" %>
    </div>
  </div>
  </div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="offset-md-1 col-md-11">
      <div class="order_detail_title">
      <h4>注文履歴詳細</h4>
    </div>
    </div>
    <div class="col-md-3">
      <h5>購入者</h5>
      <h5>注文日</h5>
      <h5>配送先</h5>
      <h5>支払方法</h5>
      <h5>注文ステータス</h5>
    </div>
    <div class="col-md-9">
      <p><%= @order.customer.first_name %><%= @order.customer.last_name %></p>
      <p><%= l @order.created_at, format: :short %></p>
      <p><%= @order.postal_code %><%= @order.address %><%= @order.name %></p>
      <p><%= @order.payment_method_i18n %></p>
      <%= form_with model: @order, url:admin_order_path, methot: :patch, local:true do |f| %>
        <p>
          <%= f.select :status, Order.statuses_i18n.invert %>
          <%= f.submit '更新', class: "btn btn-success" %>
        </p>
      <% end %>
    </div>
    <div class="col-md-9">
    <table class="table">
      <thead>
        <tr>
          <th>商品名</th>
          <th>単価（税込）</th>
          <th>数量</th>
          <th>小計</th>
          <th>製作ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @order_details.each do |order_detail| %>
          <tr>
            <td><%= order_detail.item.name %></td>
            <td><%= order_detail.item.price %></td>
            <td><%= order_detail.amount %></td>
            <td><%= order_detail.price %></td>
            <td>
              <%= form_with model: order_detail, url: admin_update_order_details_path(order_detail.id), methot: :patch, local:true do |order| %>
                <%= order.select :making_status, OrderDetail.making_statuses_i18n.invert %>
                <%= order.submit '変更', class: "btn btn-success" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>
    <div class="col-md-3">
      <table>
        <tr>
          <th>商品合計</th>
          <td><%= @order.total_payment %>円</td>
        </tr>
        <tr>
          <th>送料</th>
          <td><%= @order.shipping_cost %>円</td>
        </tr>
        <tr>
          <th>請求金額合計</th>
          <td><%= @order.total_payment + @order.shipping_cost %>円</td>
        </tr>
      </table>
    </div>
  </div>
</div>